server:
  port: 8081
# 服务注册
spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.233.71:8848


## 服务配置
      serverAddr: 192.168.233.71:8848
  config:
    import:
      - nacos:nacos-config-example.properties?refreshEnabled=true
      - nacos:remote_config.properties?refreshEnabled=true
